//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Test.HelperClasses
{
	/// <summary>Field Creation Class for entity NewtableEntity</summary>
	public partial class NewtableFields
	{
		/// <summary>Creates a new NewtableEntity.Abc field instance</summary>
		public static EntityField2 Abc { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewtableFieldIndex.Abc); }}
		/// <summary>Creates a new NewtableEntity.Cdf field instance</summary>
		public static EntityField2 Cdf { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewtableFieldIndex.Cdf); }}
		/// <summary>Creates a new NewtableEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewtableFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity ProductEntity</summary>
	public partial class ProductFields
	{
		/// <summary>Creates a new ProductEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Id); }}
		/// <summary>Creates a new ProductEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.RoleId); }}
		/// <summary>Creates a new UserEntity.UserName field instance</summary>
		public static EntityField2 UserName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UserName); }}
	}
	

}