//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Test.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal partial class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitNewtableEntityMappings();
			InitProductEntityMappings();
			InitUserEntityMappings();
		}

		/// <summary>Inits NewtableEntity's mappings</summary>
		private void InitNewtableEntityMappings()
		{
			this.AddElementMapping("NewtableEntity", @"postgres", @"public", "newtable", 3, 0);
			this.AddElementFieldMapping("NewtableEntity", "Abc", "abc", false, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("NewtableEntity", "Cdf", "cdf", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("NewtableEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.newtable_id_seq", null, typeof(System.Int32), 2);
		}

		/// <summary>Inits ProductEntity's mappings</summary>
		private void InitProductEntityMappings()
		{
			this.AddElementMapping("ProductEntity", @"postgres", @"public", "product", 2, 0);
			this.AddElementFieldMapping("ProductEntity", "Id", "id", false, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ProductEntity", "Name", "name", false, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"postgres", @"public", "user", 3, 0);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("UserEntity", "RoleId", "role_id", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "UserName", "user_name", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 2);
		}

	}
}
