//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Test.HelperClasses;
using Test.FactoryClasses;
using Test.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Test.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Newtable'.<br/><br/></summary>
	[Serializable]
	public partial class NewtableEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static NewtableEntityStaticMetaData _staticMetaData = new NewtableEntityStaticMetaData();
		private static NewtableRelations _relationsFactory = new NewtableRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class NewtableEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public NewtableEntityStaticMetaData()
			{
				SetEntityCoreInfo("NewtableEntity", InheritanceHierarchyType.None, false, (int)Test.EntityType.NewtableEntity, typeof(NewtableEntity), typeof(NewtableEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static NewtableEntity()
		{
		}

		/// <summary> CTor</summary>
		public NewtableEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public NewtableEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this NewtableEntity</param>
		public NewtableEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Newtable which data should be fetched into this Newtable object</param>
		public NewtableEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Newtable which data should be fetched into this Newtable object</param>
		/// <param name="validator">The custom validator object for this NewtableEntity</param>
		public NewtableEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected NewtableEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this NewtableEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static NewtableRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Abc property of the Entity Newtable<br/><br/></summary>
		/// <remarks>Mapped on  table field: "newtable"."abc".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Abc
		{
			get { return (System.String)GetValue((int)NewtableFieldIndex.Abc, true); }
			set { SetValue((int)NewtableFieldIndex.Abc, value); }
		}

		/// <summary>The Cdf property of the Entity Newtable<br/><br/></summary>
		/// <remarks>Mapped on  table field: "newtable"."cdf".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Cdf
		{
			get { return (System.String)GetValue((int)NewtableFieldIndex.Cdf, true); }
			set { SetValue((int)NewtableFieldIndex.Cdf, value); }
		}

		/// <summary>The Id property of the Entity Newtable<br/><br/></summary>
		/// <remarks>Mapped on  table field: "newtable"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)NewtableFieldIndex.Id, true); }
			set { SetValue((int)NewtableFieldIndex.Id, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Test
{
	public enum NewtableFieldIndex
	{
		///<summary>Abc. </summary>
		Abc,
		///<summary>Cdf. </summary>
		Cdf,
		///<summary>Id. </summary>
		Id,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Test.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Newtable. </summary>
	public partial class NewtableRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticNewtableRelations
	{

		/// <summary>CTor</summary>
		static StaticNewtableRelations() { }
	}
}
