//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Qtht.Data.HelperClasses;
using Qtht.Data.FactoryClasses;
using Qtht.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Qtht.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'AppRole'.<br/><br/></summary>
	[Serializable]
	public partial class AppRoleEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<AppUserEntity> _appUsers;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static AppRoleEntityStaticMetaData _staticMetaData = new AppRoleEntityStaticMetaData();
		private static AppRoleRelations _relationsFactory = new AppRoleRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppUsers</summary>
			public static readonly string AppUsers = "AppUsers";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppRoleEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppRoleEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppRoleEntity", InheritanceHierarchyType.None, false, (int)Qtht.Data.EntityType.AppRoleEntity, typeof(AppRoleEntity), typeof(AppRoleEntityFactory), false);
				AddNavigatorMetaData<AppRoleEntity, EntityCollection<AppUserEntity>>("AppUsers", a => a._appUsers, (a, b) => a._appUsers = b, a => a.AppUsers, () => new AppRoleRelations().AppUserEntityUsingRoleId, typeof(AppUserEntity), (int)Qtht.Data.EntityType.AppUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppRoleEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppRoleEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppRoleEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppRoleEntity</param>
		public AppRoleEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AppRole which data should be fetched into this AppRole object</param>
		public AppRoleEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AppRole which data should be fetched into this AppRole object</param>
		/// <param name="validator">The custom validator object for this AppRoleEntity</param>
		public AppRoleEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppRoleEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Code .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCCode()
		{
			var filter = new PredicateExpression();
			filter.Add(Qtht.Data.HelperClasses.AppRoleFields.Code == this.Fields.GetCurrentValue((int)AppRoleFieldIndex.Code));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppUsers() { return CreateRelationInfoForNavigator("AppUsers"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppRoleEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppRoleRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppUsers { get { return _staticMetaData.GetPrefetchPathElement("AppUsers", CommonEntityBase.CreateEntityCollection<AppUserEntity>()); } }

		/// <summary>The Code property of the Entity AppRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_role"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)AppRoleFieldIndex.Code, true); }
			set { SetValue((int)AppRoleFieldIndex.Code, value); }
		}

		/// <summary>The CreatedAt property of the Entity AppRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_role"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)AppRoleFieldIndex.CreatedAt, true); }
			set { SetValue((int)AppRoleFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Description property of the Entity AppRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_role"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppRoleFieldIndex.Description, true); }
			set { SetValue((int)AppRoleFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity AppRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_role"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)AppRoleFieldIndex.Id, true); }
			set { SetValue((int)AppRoleFieldIndex.Id, value); }
		}

		/// <summary>The Name property of the Entity AppRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_role"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)AppRoleFieldIndex.Name, true); }
			set { SetValue((int)AppRoleFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppUserEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppUserEntity))]
		public virtual EntityCollection<AppUserEntity> AppUsers { get { return GetOrCreateEntityCollection<AppUserEntity, AppUserEntityFactory>("AppRole", true, false, ref _appUsers); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Qtht.Data
{
	public enum AppRoleFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Qtht.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppRole. </summary>
	public partial class AppRoleRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppRoleEntity and AppUserEntity over the 1:n relation they have, using the relation between the fields: AppRole.Id - AppUser.RoleId</summary>
		public virtual IEntityRelation AppUserEntityUsingRoleId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppUsers", true, new[] { AppRoleFields.Id, AppUserFields.RoleId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppRoleRelations
	{
		internal static readonly IEntityRelation AppUserEntityUsingRoleIdStatic = new AppRoleRelations().AppUserEntityUsingRoleId;

		/// <summary>CTor</summary>
		static StaticAppRoleRelations() { }
	}
}
