//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Qtht.Data.HelperClasses;
using Qtht.Data.FactoryClasses;
using Qtht.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Qtht.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'AppUser'.<br/><br/></summary>
	[Serializable]
	public partial class AppUserEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<EmailVerificationTokenEntity> _emailVerificationTokens;
		private EntityCollection<PasswordResetTokenEntity> _passwordResetTokens;
		private EntityCollection<RefreshTokenEntity> _refreshTokens;
		private AppRoleEntity _appRole;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static AppUserEntityStaticMetaData _staticMetaData = new AppUserEntityStaticMetaData();
		private static AppUserRelations _relationsFactory = new AppUserRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppRole</summary>
			public static readonly string AppRole = "AppRole";
			/// <summary>Member name EmailVerificationTokens</summary>
			public static readonly string EmailVerificationTokens = "EmailVerificationTokens";
			/// <summary>Member name PasswordResetTokens</summary>
			public static readonly string PasswordResetTokens = "PasswordResetTokens";
			/// <summary>Member name RefreshTokens</summary>
			public static readonly string RefreshTokens = "RefreshTokens";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppUserEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppUserEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppUserEntity", InheritanceHierarchyType.None, false, (int)Qtht.Data.EntityType.AppUserEntity, typeof(AppUserEntity), typeof(AppUserEntityFactory), false);
				AddNavigatorMetaData<AppUserEntity, EntityCollection<EmailVerificationTokenEntity>>("EmailVerificationTokens", a => a._emailVerificationTokens, (a, b) => a._emailVerificationTokens = b, a => a.EmailVerificationTokens, () => new AppUserRelations().EmailVerificationTokenEntityUsingUserId, typeof(EmailVerificationTokenEntity), (int)Qtht.Data.EntityType.EmailVerificationTokenEntity);
				AddNavigatorMetaData<AppUserEntity, EntityCollection<PasswordResetTokenEntity>>("PasswordResetTokens", a => a._passwordResetTokens, (a, b) => a._passwordResetTokens = b, a => a.PasswordResetTokens, () => new AppUserRelations().PasswordResetTokenEntityUsingUserId, typeof(PasswordResetTokenEntity), (int)Qtht.Data.EntityType.PasswordResetTokenEntity);
				AddNavigatorMetaData<AppUserEntity, EntityCollection<RefreshTokenEntity>>("RefreshTokens", a => a._refreshTokens, (a, b) => a._refreshTokens = b, a => a.RefreshTokens, () => new AppUserRelations().RefreshTokenEntityUsingUserId, typeof(RefreshTokenEntity), (int)Qtht.Data.EntityType.RefreshTokenEntity);
				AddNavigatorMetaData<AppUserEntity, AppRoleEntity>("AppRole", "AppUsers", (a, b) => a._appRole = b, a => a._appRole, (a, b) => a.AppRole = b, Qtht.Data.RelationClasses.StaticAppUserRelations.AppRoleEntityUsingRoleIdStatic, ()=>new AppUserRelations().AppRoleEntityUsingRoleId, null, new int[] { (int)AppUserFieldIndex.RoleId }, null, true, (int)Qtht.Data.EntityType.AppRoleEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppUserEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppUserEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppUserEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppUserEntity</param>
		public AppUserEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AppUser which data should be fetched into this AppUser object</param>
		public AppUserEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AppUser which data should be fetched into this AppUser object</param>
		/// <param name="validator">The custom validator object for this AppUserEntity</param>
		public AppUserEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppUserEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'EmailVerificationToken' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoEmailVerificationTokens() { return CreateRelationInfoForNavigator("EmailVerificationTokens"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'PasswordResetToken' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPasswordResetTokens() { return CreateRelationInfoForNavigator("PasswordResetTokens"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'RefreshToken' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRefreshTokens() { return CreateRelationInfoForNavigator("RefreshTokens"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppRole' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppRole() { return CreateRelationInfoForNavigator("AppRole"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppUserEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppUserRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'EmailVerificationToken' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathEmailVerificationTokens { get { return _staticMetaData.GetPrefetchPathElement("EmailVerificationTokens", CommonEntityBase.CreateEntityCollection<EmailVerificationTokenEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PasswordResetToken' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPasswordResetTokens { get { return _staticMetaData.GetPrefetchPathElement("PasswordResetTokens", CommonEntityBase.CreateEntityCollection<PasswordResetTokenEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'RefreshToken' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRefreshTokens { get { return _staticMetaData.GetPrefetchPathElement("RefreshTokens", CommonEntityBase.CreateEntityCollection<RefreshTokenEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppRole' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppRole { get { return _staticMetaData.GetPrefetchPathElement("AppRole", CommonEntityBase.CreateEntityCollection<AppRoleEntity>()); } }

		/// <summary>The AccessFailedCount property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."access_failed_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 AccessFailedCount
		{
			get { return (System.Int32)GetValue((int)AppUserFieldIndex.AccessFailedCount, true); }
			set { SetValue((int)AppUserFieldIndex.AccessFailedCount, value); }
		}

		/// <summary>The CreatedAt property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)AppUserFieldIndex.CreatedAt, true); }
			set { SetValue((int)AppUserFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Email property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)AppUserFieldIndex.Email, true); }
			set { SetValue((int)AppUserFieldIndex.Email, value); }
		}

		/// <summary>The EmailConfirmed property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."email_confirmed".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean EmailConfirmed
		{
			get { return (System.Boolean)GetValue((int)AppUserFieldIndex.EmailConfirmed, true); }
			set { SetValue((int)AppUserFieldIndex.EmailConfirmed, value); }
		}

		/// <summary>The Id property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)AppUserFieldIndex.Id, true); }
			set { SetValue((int)AppUserFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)AppUserFieldIndex.IsActive, true); }
			set { SetValue((int)AppUserFieldIndex.IsActive, value); }
		}

		/// <summary>The LastLoginAt property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."last_login_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LastLoginAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppUserFieldIndex.LastLoginAt, false); }
			set { SetValue((int)AppUserFieldIndex.LastLoginAt, value); }
		}

		/// <summary>The LockoutEnd property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."lockout_end".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LockoutEnd
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppUserFieldIndex.LockoutEnd, false); }
			set { SetValue((int)AppUserFieldIndex.LockoutEnd, value); }
		}

		/// <summary>The PasswordHash property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."password_hash".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String PasswordHash
		{
			get { return (System.String)GetValue((int)AppUserFieldIndex.PasswordHash, true); }
			set { SetValue((int)AppUserFieldIndex.PasswordHash, value); }
		}

		/// <summary>The RoleId property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."role_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid RoleId
		{
			get { return (System.Guid)GetValue((int)AppUserFieldIndex.RoleId, true); }
			set { SetValue((int)AppUserFieldIndex.RoleId, value); }
		}

		/// <summary>The UpdatedAt property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppUserFieldIndex.UpdatedAt, false); }
			set { SetValue((int)AppUserFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserName property of the Entity AppUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "app_user"."user_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String UserName
		{
			get { return (System.String)GetValue((int)AppUserFieldIndex.UserName, true); }
			set { SetValue((int)AppUserFieldIndex.UserName, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'EmailVerificationTokenEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(EmailVerificationTokenEntity))]
		public virtual EntityCollection<EmailVerificationTokenEntity> EmailVerificationTokens { get { return GetOrCreateEntityCollection<EmailVerificationTokenEntity, EmailVerificationTokenEntityFactory>("AppUser", true, false, ref _emailVerificationTokens); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'PasswordResetTokenEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PasswordResetTokenEntity))]
		public virtual EntityCollection<PasswordResetTokenEntity> PasswordResetTokens { get { return GetOrCreateEntityCollection<PasswordResetTokenEntity, PasswordResetTokenEntityFactory>("AppUser", true, false, ref _passwordResetTokens); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'RefreshTokenEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(RefreshTokenEntity))]
		public virtual EntityCollection<RefreshTokenEntity> RefreshTokens { get { return GetOrCreateEntityCollection<RefreshTokenEntity, RefreshTokenEntityFactory>("AppUser", true, false, ref _refreshTokens); } }

		/// <summary>Gets / sets related entity of type 'AppRoleEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AppRoleEntity AppRole
		{
			get { return _appRole; }
			set { SetSingleRelatedEntityNavigator(value, "AppRole"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Qtht.Data
{
	public enum AppUserFieldIndex
	{
		///<summary>AccessFailedCount. </summary>
		AccessFailedCount,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Email. </summary>
		Email,
		///<summary>EmailConfirmed. </summary>
		EmailConfirmed,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>LastLoginAt. </summary>
		LastLoginAt,
		///<summary>LockoutEnd. </summary>
		LockoutEnd,
		///<summary>PasswordHash. </summary>
		PasswordHash,
		///<summary>RoleId. </summary>
		RoleId,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserName. </summary>
		UserName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Qtht.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppUser. </summary>
	public partial class AppUserRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppUserEntity and EmailVerificationTokenEntity over the 1:n relation they have, using the relation between the fields: AppUser.Id - EmailVerificationToken.UserId</summary>
		public virtual IEntityRelation EmailVerificationTokenEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "EmailVerificationTokens", true, new[] { AppUserFields.Id, EmailVerificationTokenFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppUserEntity and PasswordResetTokenEntity over the 1:n relation they have, using the relation between the fields: AppUser.Id - PasswordResetToken.UserId</summary>
		public virtual IEntityRelation PasswordResetTokenEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "PasswordResetTokens", true, new[] { AppUserFields.Id, PasswordResetTokenFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppUserEntity and RefreshTokenEntity over the 1:n relation they have, using the relation between the fields: AppUser.Id - RefreshToken.UserId</summary>
		public virtual IEntityRelation RefreshTokenEntityUsingUserId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "RefreshTokens", true, new[] { AppUserFields.Id, RefreshTokenFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppUserEntity and AppRoleEntity over the m:1 relation they have, using the relation between the fields: AppUser.RoleId - AppRole.Id</summary>
		public virtual IEntityRelation AppRoleEntityUsingRoleId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppRole", false, new[] { AppRoleFields.Id, AppUserFields.RoleId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppUserRelations
	{
		internal static readonly IEntityRelation EmailVerificationTokenEntityUsingUserIdStatic = new AppUserRelations().EmailVerificationTokenEntityUsingUserId;
		internal static readonly IEntityRelation PasswordResetTokenEntityUsingUserIdStatic = new AppUserRelations().PasswordResetTokenEntityUsingUserId;
		internal static readonly IEntityRelation RefreshTokenEntityUsingUserIdStatic = new AppUserRelations().RefreshTokenEntityUsingUserId;
		internal static readonly IEntityRelation AppRoleEntityUsingRoleIdStatic = new AppUserRelations().AppRoleEntityUsingRoleId;

		/// <summary>CTor</summary>
		static StaticAppUserRelations() { }
	}
}
