//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Qtht.Data.HelperClasses;
using Qtht.Data.FactoryClasses;
using Qtht.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Qtht.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'PasswordResetToken'.<br/><br/></summary>
	[Serializable]
	public partial class PasswordResetTokenEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private AppUserEntity _appUser;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PasswordResetTokenEntityStaticMetaData _staticMetaData = new PasswordResetTokenEntityStaticMetaData();
		private static PasswordResetTokenRelations _relationsFactory = new PasswordResetTokenRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppUser</summary>
			public static readonly string AppUser = "AppUser";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PasswordResetTokenEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PasswordResetTokenEntityStaticMetaData()
			{
				SetEntityCoreInfo("PasswordResetTokenEntity", InheritanceHierarchyType.None, false, (int)Qtht.Data.EntityType.PasswordResetTokenEntity, typeof(PasswordResetTokenEntity), typeof(PasswordResetTokenEntityFactory), false);
				AddNavigatorMetaData<PasswordResetTokenEntity, AppUserEntity>("AppUser", "PasswordResetTokens", (a, b) => a._appUser = b, a => a._appUser, (a, b) => a.AppUser = b, Qtht.Data.RelationClasses.StaticPasswordResetTokenRelations.AppUserEntityUsingUserIdStatic, ()=>new PasswordResetTokenRelations().AppUserEntityUsingUserId, null, new int[] { (int)PasswordResetTokenFieldIndex.UserId }, null, true, (int)Qtht.Data.EntityType.AppUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PasswordResetTokenEntity()
		{
		}

		/// <summary> CTor</summary>
		public PasswordResetTokenEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PasswordResetTokenEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PasswordResetTokenEntity</param>
		public PasswordResetTokenEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PasswordResetToken which data should be fetched into this PasswordResetToken object</param>
		public PasswordResetTokenEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PasswordResetToken which data should be fetched into this PasswordResetToken object</param>
		/// <param name="validator">The custom validator object for this PasswordResetTokenEntity</param>
		public PasswordResetTokenEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PasswordResetTokenEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: TokenHash .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCTokenHash()
		{
			var filter = new PredicateExpression();
			filter.Add(Qtht.Data.HelperClasses.PasswordResetTokenFields.TokenHash == this.Fields.GetCurrentValue((int)PasswordResetTokenFieldIndex.TokenHash));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppUser() { return CreateRelationInfoForNavigator("AppUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PasswordResetTokenEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PasswordResetTokenRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppUser { get { return _staticMetaData.GetPrefetchPathElement("AppUser", CommonEntityBase.CreateEntityCollection<AppUserEntity>()); } }

		/// <summary>The CreatedAt property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_token"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PasswordResetTokenFieldIndex.CreatedAt, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.CreatedAt, value); }
		}

		/// <summary>The ExpiresAt property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_token"."expires_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ExpiresAt
		{
			get { return (System.DateTime)GetValue((int)PasswordResetTokenFieldIndex.ExpiresAt, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.ExpiresAt, value); }
		}

		/// <summary>The Id property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_token"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)PasswordResetTokenFieldIndex.Id, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.Id, value); }
		}

		/// <summary>The TokenHash property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_token"."token_hash".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 128.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String TokenHash
		{
			get { return (System.String)GetValue((int)PasswordResetTokenFieldIndex.TokenHash, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.TokenHash, value); }
		}

		/// <summary>The UsedAt property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_token"."used_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UsedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PasswordResetTokenFieldIndex.UsedAt, false); }
			set { SetValue((int)PasswordResetTokenFieldIndex.UsedAt, value); }
		}

		/// <summary>The UserId property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_token"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)PasswordResetTokenFieldIndex.UserId, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AppUserEntity AppUser
		{
			get { return _appUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppUser"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Qtht.Data
{
	public enum PasswordResetTokenFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>ExpiresAt. </summary>
		ExpiresAt,
		///<summary>Id. </summary>
		Id,
		///<summary>TokenHash. </summary>
		TokenHash,
		///<summary>UsedAt. </summary>
		UsedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Qtht.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PasswordResetToken. </summary>
	public partial class PasswordResetTokenRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between PasswordResetTokenEntity and AppUserEntity over the m:1 relation they have, using the relation between the fields: PasswordResetToken.UserId - AppUser.Id</summary>
		public virtual IEntityRelation AppUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppUser", false, new[] { AppUserFields.Id, PasswordResetTokenFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPasswordResetTokenRelations
	{
		internal static readonly IEntityRelation AppUserEntityUsingUserIdStatic = new PasswordResetTokenRelations().AppUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticPasswordResetTokenRelations() { }
	}
}
