//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Qtht.Data.HelperClasses;
using Qtht.Data.FactoryClasses;
using Qtht.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Qtht.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'RefreshToken'.<br/><br/></summary>
	[Serializable]
	public partial class RefreshTokenEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<RefreshTokenEntity> _refreshTokens;
		private AppUserEntity _appUser;
		private RefreshTokenEntity _refreshToken;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static RefreshTokenEntityStaticMetaData _staticMetaData = new RefreshTokenEntityStaticMetaData();
		private static RefreshTokenRelations _relationsFactory = new RefreshTokenRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppUser</summary>
			public static readonly string AppUser = "AppUser";
			/// <summary>Member name RefreshToken</summary>
			public static readonly string RefreshToken = "RefreshToken";
			/// <summary>Member name RefreshTokens</summary>
			public static readonly string RefreshTokens = "RefreshTokens";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RefreshTokenEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RefreshTokenEntityStaticMetaData()
			{
				SetEntityCoreInfo("RefreshTokenEntity", InheritanceHierarchyType.None, false, (int)Qtht.Data.EntityType.RefreshTokenEntity, typeof(RefreshTokenEntity), typeof(RefreshTokenEntityFactory), false);
				AddNavigatorMetaData<RefreshTokenEntity, EntityCollection<RefreshTokenEntity>>("RefreshTokens", a => a._refreshTokens, (a, b) => a._refreshTokens = b, a => a.RefreshTokens, () => new RefreshTokenRelations().RefreshTokenEntityUsingReplacedBy, typeof(RefreshTokenEntity), (int)Qtht.Data.EntityType.RefreshTokenEntity);
				AddNavigatorMetaData<RefreshTokenEntity, AppUserEntity>("AppUser", "RefreshTokens", (a, b) => a._appUser = b, a => a._appUser, (a, b) => a.AppUser = b, Qtht.Data.RelationClasses.StaticRefreshTokenRelations.AppUserEntityUsingUserIdStatic, ()=>new RefreshTokenRelations().AppUserEntityUsingUserId, null, new int[] { (int)RefreshTokenFieldIndex.UserId }, null, true, (int)Qtht.Data.EntityType.AppUserEntity);
				AddNavigatorMetaData<RefreshTokenEntity, RefreshTokenEntity>("RefreshToken", "RefreshTokens", (a, b) => a._refreshToken = b, a => a._refreshToken, (a, b) => a.RefreshToken = b, Qtht.Data.RelationClasses.StaticRefreshTokenRelations.RefreshTokenEntityUsingIdReplacedByStatic, ()=>new RefreshTokenRelations().RefreshTokenEntityUsingIdReplacedBy, null, new int[] { (int)RefreshTokenFieldIndex.ReplacedBy }, null, true, (int)Qtht.Data.EntityType.RefreshTokenEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static RefreshTokenEntity()
		{
		}

		/// <summary> CTor</summary>
		public RefreshTokenEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RefreshTokenEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RefreshTokenEntity</param>
		public RefreshTokenEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RefreshToken which data should be fetched into this RefreshToken object</param>
		public RefreshTokenEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RefreshToken which data should be fetched into this RefreshToken object</param>
		/// <param name="validator">The custom validator object for this RefreshTokenEntity</param>
		public RefreshTokenEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RefreshTokenEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: TokenHash .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCTokenHash()
		{
			var filter = new PredicateExpression();
			filter.Add(Qtht.Data.HelperClasses.RefreshTokenFields.TokenHash == this.Fields.GetCurrentValue((int)RefreshTokenFieldIndex.TokenHash));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'RefreshToken' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRefreshTokens() { return CreateRelationInfoForNavigator("RefreshTokens"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppUser() { return CreateRelationInfoForNavigator("AppUser"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'RefreshToken' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRefreshToken() { return CreateRelationInfoForNavigator("RefreshToken"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RefreshTokenEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RefreshTokenRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'RefreshToken' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRefreshTokens { get { return _staticMetaData.GetPrefetchPathElement("RefreshTokens", CommonEntityBase.CreateEntityCollection<RefreshTokenEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppUser { get { return _staticMetaData.GetPrefetchPathElement("AppUser", CommonEntityBase.CreateEntityCollection<AppUserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'RefreshToken' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRefreshToken { get { return _staticMetaData.GetPrefetchPathElement("RefreshToken", CommonEntityBase.CreateEntityCollection<RefreshTokenEntity>()); } }

		/// <summary>The CreatedAt property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)RefreshTokenFieldIndex.CreatedAt, true); }
			set { SetValue((int)RefreshTokenFieldIndex.CreatedAt, value); }
		}

		/// <summary>The CreatedByIp property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."created_by_ip".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 45.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CreatedByIp
		{
			get { return (System.String)GetValue((int)RefreshTokenFieldIndex.CreatedByIp, true); }
			set { SetValue((int)RefreshTokenFieldIndex.CreatedByIp, value); }
		}

		/// <summary>The ExpiresAt property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."expires_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ExpiresAt
		{
			get { return (System.DateTime)GetValue((int)RefreshTokenFieldIndex.ExpiresAt, true); }
			set { SetValue((int)RefreshTokenFieldIndex.ExpiresAt, value); }
		}

		/// <summary>The Id property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)RefreshTokenFieldIndex.Id, true); }
			set { SetValue((int)RefreshTokenFieldIndex.Id, value); }
		}

		/// <summary>The ReplacedBy property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."replaced_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ReplacedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)RefreshTokenFieldIndex.ReplacedBy, false); }
			set { SetValue((int)RefreshTokenFieldIndex.ReplacedBy, value); }
		}

		/// <summary>The RevokedAt property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."revoked_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> RevokedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)RefreshTokenFieldIndex.RevokedAt, false); }
			set { SetValue((int)RefreshTokenFieldIndex.RevokedAt, value); }
		}

		/// <summary>The RevokedByIp property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."revoked_by_ip".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String RevokedByIp
		{
			get { return (System.String)GetValue((int)RefreshTokenFieldIndex.RevokedByIp, true); }
			set { SetValue((int)RefreshTokenFieldIndex.RevokedByIp, value); }
		}

		/// <summary>The RevokedReason property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."revoked_reason".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String RevokedReason
		{
			get { return (System.String)GetValue((int)RefreshTokenFieldIndex.RevokedReason, true); }
			set { SetValue((int)RefreshTokenFieldIndex.RevokedReason, value); }
		}

		/// <summary>The TokenHash property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."token_hash".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 128.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String TokenHash
		{
			get { return (System.String)GetValue((int)RefreshTokenFieldIndex.TokenHash, true); }
			set { SetValue((int)RefreshTokenFieldIndex.TokenHash, value); }
		}

		/// <summary>The UserId property of the Entity RefreshToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "refresh_token"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)RefreshTokenFieldIndex.UserId, true); }
			set { SetValue((int)RefreshTokenFieldIndex.UserId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'RefreshTokenEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(RefreshTokenEntity))]
		public virtual EntityCollection<RefreshTokenEntity> RefreshTokens { get { return GetOrCreateEntityCollection<RefreshTokenEntity, RefreshTokenEntityFactory>("RefreshToken", true, false, ref _refreshTokens); } }

		/// <summary>Gets / sets related entity of type 'AppUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AppUserEntity AppUser
		{
			get { return _appUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppUser"); }
		}

		/// <summary>Gets / sets related entity of type 'RefreshTokenEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual RefreshTokenEntity RefreshToken
		{
			get { return _refreshToken; }
			set { SetSingleRelatedEntityNavigator(value, "RefreshToken"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Qtht.Data
{
	public enum RefreshTokenFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>CreatedByIp. </summary>
		CreatedByIp,
		///<summary>ExpiresAt. </summary>
		ExpiresAt,
		///<summary>Id. </summary>
		Id,
		///<summary>ReplacedBy. </summary>
		ReplacedBy,
		///<summary>RevokedAt. </summary>
		RevokedAt,
		///<summary>RevokedByIp. </summary>
		RevokedByIp,
		///<summary>RevokedReason. </summary>
		RevokedReason,
		///<summary>TokenHash. </summary>
		TokenHash,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Qtht.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: RefreshToken. </summary>
	public partial class RefreshTokenRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between RefreshTokenEntity and RefreshTokenEntity over the 1:n relation they have, using the relation between the fields: RefreshToken.Id - RefreshToken.ReplacedBy</summary>
		public virtual IEntityRelation RefreshTokenEntityUsingReplacedBy
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "RefreshTokens", true, new[] { RefreshTokenFields.Id, RefreshTokenFields.ReplacedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between RefreshTokenEntity and AppUserEntity over the m:1 relation they have, using the relation between the fields: RefreshToken.UserId - AppUser.Id</summary>
		public virtual IEntityRelation AppUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppUser", false, new[] { AppUserFields.Id, RefreshTokenFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between RefreshTokenEntity and RefreshTokenEntity over the m:1 relation they have, using the relation between the fields: RefreshToken.ReplacedBy - RefreshToken.Id</summary>
		public virtual IEntityRelation RefreshTokenEntityUsingIdReplacedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "RefreshToken", false, new[] { RefreshTokenFields.Id, RefreshTokenFields.ReplacedBy }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRefreshTokenRelations
	{
		internal static readonly IEntityRelation RefreshTokenEntityUsingReplacedByStatic = new RefreshTokenRelations().RefreshTokenEntityUsingReplacedBy;
		internal static readonly IEntityRelation AppUserEntityUsingUserIdStatic = new RefreshTokenRelations().AppUserEntityUsingUserId;
		internal static readonly IEntityRelation RefreshTokenEntityUsingIdReplacedByStatic = new RefreshTokenRelations().RefreshTokenEntityUsingIdReplacedBy;

		/// <summary>CTor</summary>
		static StaticRefreshTokenRelations() { }
	}
}
