//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Qtht.Data.HelperClasses;
using Qtht.Data.FactoryClasses;
using Qtht.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Qtht.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'UserLogin'.<br/><br/></summary>
	[Serializable]
	public partial class UserLoginEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private AppUserEntity _appUser;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UserLoginEntityStaticMetaData _staticMetaData = new UserLoginEntityStaticMetaData();
		private static UserLoginRelations _relationsFactory = new UserLoginRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppUser</summary>
			public static readonly string AppUser = "AppUser";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UserLoginEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UserLoginEntityStaticMetaData()
			{
				SetEntityCoreInfo("UserLoginEntity", InheritanceHierarchyType.None, false, (int)Qtht.Data.EntityType.UserLoginEntity, typeof(UserLoginEntity), typeof(UserLoginEntityFactory), false);
				AddNavigatorMetaData<UserLoginEntity, AppUserEntity>("AppUser", "UserLogins", (a, b) => a._appUser = b, a => a._appUser, (a, b) => a.AppUser = b, Qtht.Data.RelationClasses.StaticUserLoginRelations.AppUserEntityUsingUserIdStatic, ()=>new UserLoginRelations().AppUserEntityUsingUserId, null, new int[] { (int)UserLoginFieldIndex.UserId }, null, true, (int)Qtht.Data.EntityType.AppUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UserLoginEntity()
		{
		}

		/// <summary> CTor</summary>
		public UserLoginEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UserLoginEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UserLoginEntity</param>
		public UserLoginEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="provider">PK value for UserLogin which data should be fetched into this UserLogin object</param>
		/// <param name="providerUserId">PK value for UserLogin which data should be fetched into this UserLogin object</param>
		public UserLoginEntity(System.String provider, System.String providerUserId) : this(provider, providerUserId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="provider">PK value for UserLogin which data should be fetched into this UserLogin object</param>
		/// <param name="providerUserId">PK value for UserLogin which data should be fetched into this UserLogin object</param>
		/// <param name="validator">The custom validator object for this UserLoginEntity</param>
		public UserLoginEntity(System.String provider, System.String providerUserId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Provider = provider;
			this.ProviderUserId = providerUserId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UserLoginEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppUser() { return CreateRelationInfoForNavigator("AppUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UserLoginEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UserLoginRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppUser { get { return _staticMetaData.GetPrefetchPathElement("AppUser", CommonEntityBase.CreateEntityCollection<AppUserEntity>()); } }

		/// <summary>The CreatedAt property of the Entity UserLogin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_login"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)UserLoginFieldIndex.CreatedAt, true); }
			set { SetValue((int)UserLoginFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Provider property of the Entity UserLogin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_login"."provider".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Provider
		{
			get { return (System.String)GetValue((int)UserLoginFieldIndex.Provider, true); }
			set { SetValue((int)UserLoginFieldIndex.Provider, value); }
		}

		/// <summary>The ProviderUserId property of the Entity UserLogin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_login"."provider_user_id".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String ProviderUserId
		{
			get { return (System.String)GetValue((int)UserLoginFieldIndex.ProviderUserId, true); }
			set { SetValue((int)UserLoginFieldIndex.ProviderUserId, value); }
		}

		/// <summary>The UserId property of the Entity UserLogin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_login"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)UserLoginFieldIndex.UserId, true); }
			set { SetValue((int)UserLoginFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AppUserEntity AppUser
		{
			get { return _appUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppUser"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Qtht.Data
{
	public enum UserLoginFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Provider. </summary>
		Provider,
		///<summary>ProviderUserId. </summary>
		ProviderUserId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Qtht.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UserLogin. </summary>
	public partial class UserLoginRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between UserLoginEntity and AppUserEntity over the m:1 relation they have, using the relation between the fields: UserLogin.UserId - AppUser.Id</summary>
		public virtual IEntityRelation AppUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppUser", false, new[] { AppUserFields.Id, UserLoginFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUserLoginRelations
	{
		internal static readonly IEntityRelation AppUserEntityUsingUserIdStatic = new UserLoginRelations().AppUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticUserLoginRelations() { }
	}
}
